--- 

- name: copy dbscript.j2 in tasks folder
  template:
    src: dbscript.j2
    dest: /home/ubuntu/kk/config-mgt-ansible/roles/mysql/tasks/dbscript.sql
    owner: root
    group: root
    mode: 0777
  delegate_to: localhost 
